# Generated by Django 5.2.12 on 2026-03-05 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KyNang',
            fields=[
                ('id_ky_nang', models.AutoField(primary_key=True, serialize=False)),
                ('ten_ky_nang', models.CharField(max_length=255)),
                ('ma_tieu_chuan', models.CharField(blank=True, max_length=100, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id_khoa_hoc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khoa_hoc', models.CharField(max_length=255)),
                ('mo_ta_chi_tiet', models.TextField(blank=True, null=True)),
                ('gia_tien', models.FloatField(default=0.0)),
                ('cong_khai', models.BooleanField(default=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('id_giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khoa_hoc_giang_day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyHoc',
            fields=[
                ('id_dang_ky', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('phan_tram_hoan_thanh', models.FloatField(default=0.0)),
                ('trang_thai_hoc', models.CharField(choices=[('DangHoc', 'Đang học'), ('DaXong', 'Đã xong'), ('Huy', 'Hủy')], default='DangHoc', max_length=50)),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hoc', to=settings.AUTH_USER_MODEL)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hoc', to='lms.khoahoc')),
            ],
        ),
        migrations.CreateModel(
            name='BaiGiang',
            fields=[
                ('id_bai_giang', models.AutoField(primary_key=True, serialize=False)),
                ('ten_bai_giang', models.CharField(max_length=255)),
                ('noi_dung_url', models.CharField(blank=True, max_length=500, null=True)),
                ('thu_tu', models.IntegerField(default=1)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_giang', to='lms.khoahoc')),
            ],
        ),
        migrations.CreateModel(
            name='KyNangKhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_do_dat_duoc', models.CharField(blank=True, max_length=100, null=True)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.khoahoc')),
                ('id_ky_nang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.kynang')),
            ],
            options={
                'unique_together': {('id_khoa_hoc', 'id_ky_nang')},
            },
        ),
    ]
