# Generated by Django 5.2.12 on 2026-03-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baigiang',
            options={'ordering': ['thu_tu']},
        ),
        migrations.AddField(
            model_name='baigiang',
            name='la_xem_truoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baigiang',
            name='loai_bai',
            field=models.CharField(choices=[('Video', 'Video bài giảng'), ('Quiz', 'Bài kiểm tra'), ('TaiLieu', 'Tài liệu')], default='Video', max_length=50),
        ),
        migrations.AddField(
            model_name='baigiang',
            name='thoi_luong_phut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='danh_muc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='gia_goc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='hinh_anh_thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='mo_ta_ngan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='trinh_do',
            field=models.CharField(choices=[('CoSo', 'Cơ sở'), ('TrungCap', 'Trung cấp'), ('NangCao', 'Nâng cao')], default='CoSo', max_length=50),
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id_chuong', models.AutoField(primary_key=True, serialize=False)),
                ('ten_chuong', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('thu_tu', models.IntegerField(default=1)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuong_set', to='lms.khoahoc')),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.AddField(
            model_name='baigiang',
            name='id_chuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_giang', to='lms.chuong'),
        ),
    ]
