# Generated by Django 5.2.12 on 2026-03-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_baigiang_options_baigiang_la_xem_truoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baigiang',
            name='video_watch_percentage',
            field=models.IntegerField(default=100, help_text='Với bài Video: % thời lượng cần xem để hoàn thành (33, 66, 100). Không dùng cho loại bài khác.'),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='is_sequential',
            field=models.BooleanField(default=False, help_text='Bật chế độ học tuần tự: phải hoàn thành bài trước mới mở được bài sau'),
        ),
        migrations.CreateModel(
            name='TienDoBaiGiang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_hoan_thanh', models.BooleanField(default=False)),
                ('ngay_hoan_thanh', models.DateTimeField(blank=True, null=True)),
                ('id_bai_giang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tien_do', to='lms.baigiang')),
                ('id_dang_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tien_do_bai', to='lms.dangkyhoc')),
            ],
            options={
                'unique_together': {('id_dang_ky', 'id_bai_giang')},
            },
        ),
    ]
