# Generated by Django 5.2.12 on 2026-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_baigiang_video_watch_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baigiang',
            name='loai_bai',
            field=models.CharField(choices=[('Video', 'Video bài giảng'), ('Quiz', 'Bài kiểm tra'), ('TaiLieu', 'Tài liệu'), ('VanBan', 'Văn bản')], default='Video', max_length=50),
        ),
        migrations.AlterField(
            model_name='baigiang',
            name='noi_dung_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
