# Generated by Django 4.2.7 on 2026-03-19 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0004_alter_baigiang_loai_bai_alter_baigiang_noi_dung_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='so_nguoi_da_hoan_thanh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='so_nguoi_dang_hoc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='tong_so_danh_gia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='trung_binh_sao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='baigiang',
            name='video_watch_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='is_sequential',
            field=models.BooleanField(default=False, help_text='Bật chế độ học tuần tự'),
        ),
        migrations.CreateModel(
            name='DanhGiaKhoaHoc',
            fields=[
                ('id_danh_gia', models.AutoField(primary_key=True, serialize=False)),
                ('so_sao', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5)),
                ('nhan_xet', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='lms.khoahoc')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_khoa_hoc', 'id_nguoi_dung')},
            },
        ),
    ]
