# Generated by Django 4.2.7 on 2026-03-19 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0005_khoahoc_so_nguoi_da_hoan_thanh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id_tin_nhan', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('id_nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_da_gui', to=settings.AUTH_USER_MODEL)),
                ('id_nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_da_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_gui'],
            },
        ),
    ]
