# Generated by Django 4.2.7 on 2026-03-19 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0006_tinnhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='tong_so_danh_gia_ntd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='trung_binh_sao_ntd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='DanhGiaNhaTuyenDung',
            fields=[
                ('id_danh_gia', models.AutoField(primary_key=True, serialize=False)),
                ('so_sao_phu_hop', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5)),
                ('nhan_xet_chuyen_mon', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_ntd', to='lms.khoahoc')),
                ('id_nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_khoa_hoc', 'id_nha_tuyen_dung')},
            },
        ),
    ]
