# Generated by Django 4.2.7 on 2026-03-19 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0007_khoahoc_tong_so_danh_gia_ntd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='so_nguoi_co_viec_lam',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TuyenDung',
            fields=[
                ('id_tuyen_dung', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tuyen', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('id_hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duoc_tuyen_dung', to=settings.AUTH_USER_MODEL)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.khoahoc')),
                ('id_nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_da_tuyen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_nha_tuyen_dung', 'id_hoc_vien', 'id_khoa_hoc')},
            },
        ),
    ]
