# Generated by Django 4.2.7 on 2026-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_khoahoc_so_nguoi_co_viec_lam_tuyendung'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuyendung',
            name='trang_thai',
            field=models.CharField(choices=[('ChoXacNhan', 'Chờ xác nhận'), ('DaDongY', 'Đã đồng ý'), ('TuChoi', 'Từ chối')], default='ChoXacNhan', max_length=20),
        ),
    ]
