# Generated by Django 5.2.12 on 2026-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_tuyendung_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
    ]
