# Generated by Django 5.2.12 on 2026-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_tinnhan_is_recalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='da_xem',
            field=models.BooleanField(default=False),
        ),
    ]
