# Generated by Django 4.2.29 on 2026-04-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_add_da_xem_to_tinnhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id_cau_hoi', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung', models.TextField()),
                ('diem', models.FloatField(default=1.0)),
                ('thu_tu', models.IntegerField(default=1)),
                ('id_bai_giang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_set', to='lms.baigiang')),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='LuaChon',
            fields=[
                ('id_lua_chon', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung', models.TextField()),
                ('la_dap_an_dung', models.BooleanField(default=False)),
                ('id_cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lua_chon_set', to='lms.cauhoi')),
            ],
        ),
        migrations.CreateModel(
            name='KetQuaQuiz',
            fields=[
                ('id_ket_qua', models.AutoField(primary_key=True, serialize=False)),
                ('diem_so', models.FloatField()),
                ('tong_diem', models.FloatField()),
                ('da_dat', models.BooleanField(default=False)),
                ('ngay_lam', models.DateTimeField(auto_now_add=True)),
                ('id_bai_giang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.baigiang')),
                ('id_dang_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_quiz', to='lms.dangkyhoc')),
            ],
        ),
    ]
