# Generated by Django 4.2.29 on 2026-04-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_cauhoi_luachon_ketquaquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='url_video_preview',
            field=models.CharField(blank=True, help_text='URL video preview (YouTube embed URL)', max_length=500, null=True),
        ),
    ]
