# Generated by Django 5.2.12 on 2026-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_add_url_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='baigiang',
            name='is_proctored',
            field=models.BooleanField(default=False),
        ),
    ]
