# Generated by Django 4.2.7 on 2026-03-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('HocVien', 'Học viên'), ('GiangVien', 'Giảng viên'), ('QuanTri', 'Quản trị viên'), ('NguoiXacThuc', 'Người xác thực'), ('NhaTuyenDung', 'Nhà tuyển dụng')], default='HocVien', max_length=50),
        ),
    ]
