# Generated by Django 4.2.7 on 2026-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nguoidung_vai_tro'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='ky_nang',
            field=models.TextField(blank=True, help_text='Danh sách kỹ năng cách nhau dấu phẩy', null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='ready_to_work',
            field=models.BooleanField(default=True),
        ),
    ]
