# Generated by Django 5.2.12 on 2026-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nguoidung_bio_nguoidung_ky_nang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='hinh_anh_logo',
            field=models.CharField(blank=True, help_text='Link ảnh đại diện hoặc logo doanh nghiệp', max_length=500, null=True),
        ),
    ]
