# Generated by Django 5.2.12 on 2026-04-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nguoidung_hinh_anh_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='hinh_anh_logo',
            field=models.TextField(blank=True, help_text='Link ảnh hoặc dữ liệu Base64 của logo/avatar', null=True),
        ),
    ]
