# Generated by Django 5.2.12 on 2026-03-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauChungChi',
            fields=[
                ('id_mau', models.AutoField(primary_key=True, serialize=False)),
                ('ten_mau', models.CharField(max_length=255)),
                ('hinh_nen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('vi_tri_chu_ky', models.CharField(blank=True, max_length=100, null=True)),
                ('id_khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mau_chung_chi', to='lms.khoahoc')),
            ],
        ),
        migrations.CreateModel(
            name='ChungChiSo',
            fields=[
                ('ma_uuid_chung_chi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ngay_cap', models.DateTimeField(auto_now_add=True)),
                ('ngay_het_han', models.DateTimeField(blank=True, null=True)),
                ('link_xac_thuc', models.CharField(blank=True, max_length=500, null=True)),
                ('chuoi_hash_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai', models.CharField(choices=[('HieuLuc', 'Hiệu lực'), ('DaThuHoi', 'Đã thu hồi')], default='HieuLuc', max_length=50)),
                ('id_dang_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chung_chi', to='lms.dangkyhoc')),
                ('id_mau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.mauchungchi')),
            ],
        ),
        migrations.CreateModel(
            name='NhatKyXacThuc',
            fields=[
                ('id_nhat_ky', models.AutoField(primary_key=True, serialize=False)),
                ('nguoi_kiem_tra', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_xem', models.DateTimeField(auto_now_add=True)),
                ('ly_do', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_uuid_chung_chi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhat_ky_xac_thuc', to='certificates.chungchiso')),
            ],
        ),
    ]
